### ISSUE TITLE
(time) time-elements package itself has been reported deprecated, use relative-time-element instead

### ISSUE THREAD

**Issue by JOELwindows7** [BryceRussell/astro-github-elements#1]
# GitHub's Time Element package deprecated
Please have a look at https://github.com/github/relative-time-element & consider migrating this wrapper in favor of this new package.

This issue is for the `@astro-github-elements/time`.

doing `npm upgrade` with this current wrapper installed
```
PS W:\starring codes\Astro Projects\perkedel-astro> npm upgrade
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated @github/time-elements@3.6.0: Please use @github/relative-time-element insteadd
npm WARN deprecated @vidstack/player@1.6.5: This package has moved to vidstack: https://github.com/vidstack/player/discussions/716

added 11 packages, removed 59 packages, changed 142 packages, and audited 834 packages in 8m

223 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 moderate, 7 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
PS W:\starring codes\Astro Projects\perkedel-astro> npm i astro@latest
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

up to date, audited 834 packages in 15s

223 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (1 moderate, 7 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

Notice the **`npm WARN deprecated @github/time-elements@3.6.0: Please use @github/relative-time-element insteadd`** where time-element is dependency used in this wrapper integration.

**Comment by BryceRussell** [comment]
Thanks for the heads up, Ill start work on removing the old package and porting it to the newer/working one

**Comment by BryceRussell** [comment]
@JOELwindows7 I just pushed the update, let me know how it works out

**Comment by JOELwindows7** [comment]
> @JOELwindows7 I just pushed the update, let me know how it works out
# Um, you forgot to tell the `package.json` ship the `Time.astro` itself..
It error missing
![image](https://user-images.githubusercontent.com/7281060/217012635-0f6ac061-bf39-4a8d-b0d1-f0d61f50f259.png)

and if I looked at this package `node_modules` directory, it missing the `Time.astro`
![image](https://user-images.githubusercontent.com/7281060/217013203-f00a63e6-c124-46e3-a746-18683d5e9ffa.png)

yeah no wonder it fail. Pls fix the forgot. check the `package.json` file again! thancc.
Here's the package information (`package.json`) from that `npm i @astro-github-elements/time` I got.
```json
{
  "name": "@astro-github-elements/time",
  "version": "0.1.0",
  "author": "Bryce Russell",
  "license": "MIT",
  "description": "An Astro wrapper for the '@github/relative-time-element' package",
  "keywords": [
    "astro",
    "astro-component",
    "astro-bryceguy",
    "github-elements",
    "web component",
    "date",
    "time"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/BryceRussell/astro-github-elements.git"
  },
  "bugs": {
    "url": "https://github.com/BryceRussell/astro-github-elements/issues"
  },
  "homepage": "https://github.com/BryceRussell/astro-github-elements/tree/main/packages/time#readme",
  "type": "module",
  "main": "./index.js",
  "exports": "./index.js",
  "files": [
    "index.js",
    "RelativeTime.astro"
  ],
  "dependencies": {
    "@github/relative-time-element": "^4.2.0"
  }
}

```
I believe you forgot to do something with the... `files` array there.

**Comment by BryceRussell** [comment]
@JOELwindows7 Sorry about that, I fixed it now. For some reason my npm workspace did not catch this error

**Comment by JOELwindows7** [comment]
> @JOELwindows7 Sorry about that, I fixed it now. For some reason my npm workspace did not catch this error

# Okay fixed. It works now!
Just as I have seen it,
![image](https://user-images.githubusercontent.com/7281060/217016550-048bb506-abc7-4bcf-bf79-61d6ea155931.png)
![image](https://user-images.githubusercontent.com/7281060/217016660-069867a8-bb88-478a-b4bc-cbcac6a9d52b.png)
it's there now!

yey it works!
![image](https://user-images.githubusercontent.com/7281060/217016765-34045a1c-ca27-4a80-b768-3ac417b4fed3.png)

**Comment by BryceRussell** [comment]
🥳 I am glad it's working, let me know if you have other issues 👊
